### ISSUE TITLE
should you be using 'react-native link' ?

### ISSUE THREAD

**Issue by brunovianarezende** [alvelig/react-native-maps-example#1]
Per the react-native-maps instructions, 'react-native link' should not be used. But, in this example you used it. Is this correct? and a related question: why 'react-native link' should not be used?

**Comment by alvelig** [comment]
For pods version you should not. Thank you for pointing out, it should go in Pods section, not general installation section.

**Comment by brunovianarezende** [comment]
A related question, is it possible to install react-native-maps in IOS without using pods?

**Comment by alvelig** [comment]
I was tired when reviewing PR for new Installation LOL It was present before there.

Without pods:
Run `react-native link react-native-maps`
If you want to use Apple Maps, you just use it. All required libs are already there (MapKit)
If you want to use Google Maps on iOS you need to link Google Maps for iOS SDK. Follow that link (Step 2 does what you want): https://developers.google.com/maps/documentation/ios-sdk/start#step_2_install_the_sdk

**Comment by brunovianarezende** [comment]
Thanks for the explanation!
